# Generated by Django 3.2.5 on 2021-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='set1_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='set2_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='set3_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
