# Generated by Django 3.2.5 on 2021-07-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0002_auto_20210714_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='set3_enabled',
            field=models.IntegerField(default=0),
        ),
    ]
