# Generated by Django 3.2.5 on 2021-07-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0003_alter_tank_set3_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='feed_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tank',
            name='set3_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
