# Generated by Django 3.2.5 on 2021-07-15 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0004_auto_20210715_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='last_feeding_time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
