# Generated by Django 3.2.5 on 2021-07-15 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0005_tank_last_feeding_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='last_feeding_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
