# Generated by Django 3.2.5 on 2021-07-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_planner', '0007_feeding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='tank_number',
            field=models.IntegerField(choices=[(0, 'مخزن1'), (1, 'مخزن2'), (2, 'مخزن3')]),
        ),
    ]
